BOT_TRAINING = "BOT TRAINING"
BOT_TRAINING_MESSAGE = "Training begins in 3 seconds"
LOCATION_STORED = "Location Detection"
LOCATION_STORED_MESSAGE = "Location traced for click at "
SCREEN_MODE="SCREEN"
KEYBOARD_MODE="KEYBOARD"
MODE_SWITCH="MODE CHANGED"
MODE_SWITCH_TO="Mode switched to"

# KEYBOARD KEYS
KEYBOARD_ALT='alt'
KEYBOARD_CTRL='ctrl'